version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stock-monitor-backend
    ports:
      - "8889:8888"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stock-monitor-frontend
    ports:
      - "8888:8888"
    depends_on:
      - backend
    restart: unless-stopped 