name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]  # 或者你的主分支名称
  workflow_dispatch:    # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USERNAME }}/StockTest
            if [ ! -d ".git" ]; then
              git clone ${{ github.server_url }}/${{ github.repository }} .
            else
              git fetch --all
              git reset --hard origin/main
            fi
            docker-compose down
            docker system prune -f --volumes
            docker-compose up -d --build 